MODE: W2W_Hybrid_Bonding_Modeling
OUTPUT_DIR: output/
INPUT_DIR: input/
DEBUG: false
DESIGN: design_6
INTERFACE: Memory_DRAM_3_From_Memory_DRAM_2
PITCH_r_um: 10.0
PITCH_c_um: 10.0
DIE_W_um: 7071.068
DIE_L_um: 7071.068
WAF_R_um: 150000
PAD_BOT_R_um: 2.5
PAD_TOP_R_um: 2.5
PAD_ARR_ROW: 707
PAD_ARR_COL: 707
VOID_SHAPE: circle
dice_width: 100
pad_yield_flag: false
pad_yield_map_sub_factor: 1
PAD_ARRANGE_PATTERN: rectangular
B_Chip_Cu_V: 0.4
B_Chip_Sio2_V: 0.6
B_Chip_Si_V: 0.0
B_Chip_T: 3.2e-06
B_Sub_Cu_V: 0.1
B_Sub_Sio2_V: 0.0
B_Sub_Si_V: 0.9
B_Sub_T: 0.000775
S_INIT_A_M: 0.0001
T_Chip_Cu_V: 0.3
T_Chip_Sio2_V: 0.7
T_Chip_Si_V: 0.0
T_Chip_T: 3.2e-06
T_Sub_Cu_V: 0.1
T_Sub_Sio2_V: 0.0
T_Sub_Si_V: 0.9
T_Sub_T: 0.000775
S_INIT_B_M: 0.0
CONTACT_AREA_CONSTRAINT: 0.75
CRITICAL_DIST_CONSTRAINT: 0.75
num_samples: 1000
RANDOM_MISALIGNMENT_MEAN_um: 0
RANDOM_MISALIGNMENT_STD_um: 0.02
SYSTEM_TRANSLATION_X_MEAN_um: 0
SYSTEM_TRANSLATION_X_STD_um: 0.02
SYSTEM_TRANSLATION_Y_MEAN_um: 0
SYSTEM_TRANSLATION_Y_STD_um: 0.02
SYSTEM_ROTATION_MEAN_rad: 5.0e-07
SYSTEM_ROTATION_STD_rad: 1.0e-07
BOW_DIFFERENCE_MEAN_um: 5
BOW_DIFFERENCE_STD_um: 1
k_mag: 0.1
M_0: 0
D0: 1.0e-09
z: 3
t_0: 0.1
k_r: 0.00018
k_r0: 230
k_L: 0.062
k_n: 9.0e-05
k_S: 2.7
TOP_DISH_MEAN_nm: -2
TOP_DISH_STD_L_nm: 0.35
TOP_DISH_STD_T_nm: 0.27
TOP_DISH_STD_E_nm: 0.22
BOT_DISH_MEAN_nm: -2
BOT_DISH_STD_L_nm: 0.35
BOT_DISH_STD_T_nm: 0.27
BOT_DISH_STD_E_nm: 0.22
TL_um: 50
k_et: 0.053
k_eb: 0.053
T_R: 25
T_anl: 300
CU_E_GPA: 91.8
CU_NU: 0.34
CU_ALPHA_PPM: 17.6
OX_E_GPA: 73.0
OX_NU: 0.17
OX_ALPHA_PPM: 0.5
SI_E_GPA: 131.0
SI_NU: 0.28
SI_ALPHA_PPM: 2.6
SIGMA_Y_MPA: 321.0
C_HEAT_E: 1.005319e-12
C_HEAT_P: 6.088622e-06
C_COOL_E: 3.375203e-06
C_COOL_P: 3.721387e-06
EXP_PHI: 0.206576
BAUSCHINGER: 0.208455
EXP_INVPHI: 0.1
EXP_AREA: 0.0465
KN_DEN_M: 1.7310513e-05
Asperity_R_m: 2.0e-06
Roughness_sigma_m: 5.0e-10
eta_s: 40000000000000.0
Roughness_constant: 0.07
Adhesion_energy: 1.3
Dielectric_Young_modulus_Pa: 73000000000.0
Dielectric_thickness: 1.5e-06
DISH_0_m: 7.5e-08
k_peel: 6660000000000000.0
CRIT_aY2_UM: 1.9
GC_SIO2_JPM2: 2.0
GC_CU_JPM2: 25.0
Effective_Contact_Area: 1.0
TILT_X_MEAN_DEG: 0.0
TILT_X_STD_DEG: 0.01
TILT_Y_MEAN_DEG: 0.0
TILT_Y_STD_DEG: 0.01
n_tilts_samples: 10000
n_dishes_samples: 10000
plot_flag: true
INTERFACE_TOP: Memory_DRAM_3
INTERFACE_BOT: Memory_DRAM_2
PAD_ARR_L_um: 7060.0
PAD_ARR_W_um: 7060.0
SYSTEM_MAGNIFICATION_MEAN_ppm: 5.0e-07
SYSTEM_MAGNIFICATION_STD_ppm: 1.0000000000000002e-08
