MODE: D2W_Hybrid_Bonding_Simulation
OUTPUT_DIR: output/
INPUT_DIR: input/
DEBUG: false
DESIGN: design_6
INTERFACE: Memory_DRAM_3_From_Memory_DRAM_2
NUM_DIE_STACKS: 10000
SIM_BATCH_SIZE: 10
PITCH_r_um: 10.0
PITCH_c_um: 10.0
DIE_W_um: 7071.068
DIE_L_um: 7071.068
PAD_ARR_ROW: 707
PAD_ARR_COL: 707
PAD_BOT_R_um: 2.5
PAD_TOP_R_um: 2.5
VOID_SHAPE: circle
dice_width: 100
pad_yield_flag: true
pad_yield_map_sub_factor: 1
PAD_ARRANGE_PATTERN: rectangular
B_Chip_Cu_V: 0.4
B_Chip_Sio2_V: 0.6
B_Chip_Si_V: 0.0
B_Chip_T: 3.2e-06
B_Sub_Cu_V: 0.1
B_Sub_Sio2_V: 0.0
B_Sub_Si_V: 0.9
B_Sub_T: 0.000775
S_INIT_A_M: 1.1111111702360891e-08
T_Chip_Cu_V: 0.3
T_Chip_Sio2_V: 0.7
T_Chip_Si_V: 0.0
T_Chip_T: 3.2e-06
T_Sub_Cu_V: 0.1
T_Sub_Sio2_V: 0.0
T_Sub_Si_V: 0.9
T_Sub_T: 0.000775
S_INIT_B_M: 0.0
CONTACT_AREA_CONSTRAINT: 0.75
CRITICAL_DIST_CONSTRAINT: 0.75
RANDOM_MISALIGNMENT_MEAN_um: 0
RANDOM_MISALIGNMENT_STD_um: 0.02
SYSTEM_TRANSLATION_X_MEAN_um: 0
SYSTEM_TRANSLATION_X_STD_um: 0.02
SYSTEM_TRANSLATION_Y_MEAN_um: 0
SYSTEM_TRANSLATION_Y_STD_um: 0.02
SYSTEM_ROTATION_MEAN_rad: 6.0e-05
SYSTEM_ROTATION_STD_rad: 1.0e-05
BOW_DIFFERENCE_MEAN_um: 0.5
BOW_DIFFERENCE_STD_um: 0.1
k_mag: 0.1
M_0: 0
first_contact: center
D0: 1.0e-09
z: 3
t_0: 0.1
k_r: 0.00018
k_r0: 230
k_L: 0.062
k_n: 9.0e-05
k_S: 2.7
TOP_DISH_MEAN_nm: -1.0
TOP_DISH_STD_nm: 0.25
BOT_DISH_MEAN_nm: -1.0
BOT_DISH_STD_nm: 0.25
k_et: 0.053
k_eb: 0.053
T_R: 25
T_anl: 300
CU_E_GPA: 91.8
CU_NU: 0.34
CU_ALPHA_PPM: 17.6
OX_E_GPA: 73.0
OX_NU: 0.17
OX_ALPHA_PPM: 0.5
SI_E_GPA: 131.0
SI_NU: 0.28
SI_ALPHA_PPM: 2.6

# === Cu & Sio2 peeling stress model Parameters ===
# === heat up and dwell stage ===
SIGMA_Y_MPA: 321.0                    # Elastic yield point (MPa)
C_HEAT_E: 1.005319e-12                       # Eq.(29) coefficient for sigma_e
C_HEAT_P: 6.088622e-6                       # Eq.(29) coefficient for sigma_p
C_COOL_E: 3.375203e-6                       # Eq.(35) coefficient for sigma_e,cool
C_COOL_P: 3.721387e-6                       # Eq.(35) coefficient for sigma_p,cool
EXP_PHI: 0.206576                          # Eq.(30)
BAUSCHINGER: 0.208455                      # Eq.(33)
EXP_INVPHI: 0.1                       # Eq.(36)
EXP_AREA: 0.0465                         # Eq.(36)
KN_DEN_M: 17.310513e-6                         # Eq.(31) denominator length in meters

Asperity_R_m: 2.0e-06
Roughness_sigma_m: 5.0e-10
eta_s: 40000000000000.0
Roughness_constant: 0.07
Adhesion_energy: 1.2
Dielectric_Young_modulus_Pa: 73000000000.0
Dielectric_thickness: 1.5e-06
DISH_0_m: 7.5e-08
k_peel: 6660000000000.0
CRIT_aY2_UM: 1.9
GC_SIO2_JPM2: 2.0
GC_CU_JPM2: 25.0
Effective_Contact_Area: 1.0
TILT_X_MEAN_DEG: 0.01
TILT_X_STD_DEG: 0.0001
TILT_Y_MEAN_DEG: 0.0
TILT_Y_STD_DEG: 0.0001
simulation_times: 1
approximate_set: 1
plot_flag: true
INTERFACE_TOP: Memory_DRAM_3
INTERFACE_BOT: Memory_DRAM_2
PAD_ARR_L_um: 7060.0
PAD_ARR_W_um: 7060.0
SYSTEM_MAGNIFICATION_MEAN_ppm: 5.0000000000000004e-08
SYSTEM_MAGNIFICATION_STD_ppm: 1.0000000000000004e-10
eff_DIE_R: 5000.000133031199
